<script lang="ts">
  import { ComponentColor } from "$lib/ui";

  import type { SVGAttributes } from "svelte/elements";

  import { z } from "zod";

  interface Props extends SVGAttributes<SVGElement> {
    color?: z.infer<typeof ComponentColor> | "invert";
  }

  let { color = "default", ...props }: Props = $props();
</script>

<svg
  data-icon="true"
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 100 100"
  preserveAspectRatio="xMidYMid"
  width="200"
  height="200"
  style="shape-rendering: auto; display: block; background: transparent;"
  data-color={color}
  {...props}
>
  <g>
    <circle
      stroke-linecap="round"
      fill="none"
      stroke-dasharray="50.26548245743669 50.26548245743669"
      stroke="var(--color-400)"
      stroke-width="8"
      r="32"
      cy="50"
      cx="50"
    >
      <animateTransform
        values="0 50 50;360 50 50"
        keyTimes="0;1"
        repeatCount="indefinite"
        dur="1s"
        type="rotate"
        attributeName="transform"
      />
    </circle>
    <circle
      stroke-linecap="round"
      fill="none"
      stroke-dashoffset="36.12831551628262"
      stroke-dasharray="36.12831551628262 36.12831551628262"
      stroke="var(--color-300)"
      stroke-width="8"
      r="23"
      cy="50"
      cx="50"
    >
      <animateTransform
        values="0 50 50;-360 50 50"
        keyTimes="0;1"
        repeatCount="indefinite"
        dur="1s"
        type="rotate"
        attributeName="transform"
      />
    </circle>
  </g><!-- [ldio] generated by https://loading.io -->
</svg>
