version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "chore(dev-deps):"
      include: "scope"
    open-pull-requests-limit: 0
