name: build

on:
  workflow_run:
    workflows: [test]
    types: [completed]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install dependencies
        run: npm install
      - name: build the application
        run: npm run build
  build-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      PORT: 8080
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: build the docker image
        run: docker build .
  build-npm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install dependencies
        run: npm install
      - name: build the npm package
        run: npm run registry:build:clean && npm run registry:build:compile
