name: deploy prod

on:
  workflow_run:
    workflows: [build]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: uikit-frontend
          region: europe-west9
          project_id: ${{ secrets.PROJECT_ID }}
          source: ./
          flags: '--concurrency=100 --timeout=60 --min-instances=1 --max-instances=10 --memory=512Mi --cpu=1 --platform=managed --allow-unauthenticated'
      - name: show output
        run: echo ${{ steps.deploy.outputs.url }}
